apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tru-activity-frontend
  annotations:
    run.googleapis.com/allow-unauthenticated: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/timeout: "300s"
        app.version: "v1.0.3"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/PROJECT_ID/tru-activity-frontend:latest
          ports:
            - name: http1
              containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3