apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tru-activity-frontend
  annotations:
    run.googleapis.com/invoker-iam-disabled: true
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/timeout: "600s"
        app.version: "v1.0.3"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/$PROJECT_ID/tru-activity-frontend:latest
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PUBLIC_API_URL
              value: "BACKEND_URL_PLACEHOLDER"
            - name: PUBLIC_GRAPHQL_URL
              value: "BACKEND_URL_PLACEHOLDER/query"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3